### ISSUE TITLE
[enhancement] 建议不要使用明文 POST 传输数据

### ISSUE THREAD

**Issue by FoliageOwO** [liyupi/ikun-test#2]
通过 POST `https://ikun-test-974538-1256524210.ap-shanghai.run.tcloudbase.com/api/question/list` 即可获取答案，但是不全，可以多次 POST 来获取整个题库的答案和每个选项的分值。

可以利用这个漏洞轻轻松松拿上 50 分，坐稳第一名。

**Comment by FoliageOwO** [comment]
我发现提交是 POST 了 `https://ikun-test-974538-1256524210.ap-shanghai.run.tcloudbase.com/api/user_score/add` 这个 API，但是一直返回 `40000` 不知道为什么。估计是做了 ID 检查？或者是 POST 的时候需要 `headers`？
```json
{"code": 40000, "data": null}
```

**Comment by FoliageOwO** [comment]
> 通过 POST `https://ikun-test-974538-1256524210.ap-shanghai.run.tcloudbase.com/api/question/list` 即可获取答案，但是不全，可以多次 POST 来获取整个题库的答案和每个选项的分值。
> 
> 可以利用这个漏洞轻轻松松拿上 50 分，坐稳第一名。

好像可以直接在源码找到 :[

**Comment by liyupi** [comment]
哈哈哈，你发现了，因为代码都是开源的，我也没有对答案做脱敏了（不过确实应该补上）
