### ISSUE TITLE
网站打不开了

### ISSUE THREAD

**Issue by DuckBurnIncense** [liyupi/ikun-test#4]
![image](https://user-images.githubusercontent.com/87637270/181308290-3832b144-cdee-4731-962f-dcfd5c102dd7.png)
恭喜鱼皮, 网站打不开了(￣y▽,￣)╭

**Comment by liyupi** [comment]
不要紧张，不用挂任何代理，晚点再试试~

**Comment by FeletexGee** [comment]
~~哎呦，你干嘛~~

**Comment by DuckBurnIncense** [comment]
成功clone到本地并运行成功了 （￣︶￣）↗
