### ISSUE TITLE
Server access issue

### ISSUE THREAD

**Issue by FeletexGee** [liyupi/ikun-test#5]
Yupi,can you use a better Tencent cloud server?ikun will be glad:-)
鱼皮，换个好点的服务器吧，虽然是腾讯云但是真的卡……bilibili 百万ikun都等不及了哈哈哈
`#print('小鱼皮露出鸡脚了吧哈哈哈，等我鸽鸽从烤箱里出来给你发律师函')`

**Comment by liyupi** [comment]
抱歉，用的是国外的免费的服务器哈

**Comment by FeletexGee** [comment]
> 抱歉，用的是国外的免费的服务器哈

不会是Github Pages部署的吧（白嫖党狂喜）
